In [1]:
import pandas as pd
import numpy as np

In [2]:
dataset = pd.read_csv("./Social_Network_Ads.csv")

In [3]:
dataset.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [4]:
dataset.drop(axis=1,columns="User ID",inplace=True)

In [5]:
#No of entries
print(len(dataset))

400


In [6]:
dataset.head()

Gender  Age  EstimatedSalary  Purchased
0    Male   19            19000          0
1    Male   35            20000          0
2  Female   26            43000          0
3  Female   27            57000          0
4    Male   19            76000          0

In [7]:
Y = dataset.iloc[:,-1]
Y.head()

0    0
1    0
2    0
3    0
4    0
Name: Purchased, dtype: int64

In [27]:
X = dataset.iloc[:,:3]
X.head()

Gender  Age  EstimatedSalary
0    Male   19            19000
1    Male   35            20000
2  Female   26            43000
3  Female   27            57000
4    Male   19            76000

In [38]:
sex = pd.get_dummies(X["Gender"],drop_first=True)
# x = sex.stack()
# x
# pd.Series(pd.Categorical(x[x!=0].index.get_level_values(1)))

In [39]:
sex.head()

Male
0     1
1     1
2     0
3     0
4     1

In [40]:
X = pd.concat([X,sex],axis=1,)

In [41]:
X.head()

Gender  Age  EstimatedSalary  Male
0    Male   19            19000     1
1    Male   35            20000     1
2  Female   26            43000     0
3  Female   27            57000     0
4    Male   19            76000     1

In [42]:
X.drop(axis=1,columns="Gender",inplace=True)

In [43]:
X.head(15)

Age  EstimatedSalary  Male
0    19            19000     1
1    35            20000     1
2    26            43000     0
3    27            57000     0
4    19            76000     1
5    27            58000     1
6    27            84000     0
7    32           150000     0
8    25            33000     1
9    35            65000     0
10   26            80000     0
11   26            52000     0
12   20            86000     1
13   32            18000     1
14   18            82000     1

In [44]:
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
X = sc_X.fit_transform(X)

In [45]:
X

array([[-1.78179743, -1.49004624,  1.02020406],
       [-0.25358736, -1.46068138,  1.02020406],
       [-1.11320552, -0.78528968, -0.98019606],
       ...,
       [ 1.17910958, -1.46068138, -0.98019606],
       [-0.15807423, -1.07893824,  1.02020406],
       [ 1.08359645, -0.99084367, -0.98019606]])

In [46]:
from sklearn.cross_validation import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,Y,test_size=1/3,random_state=42)

In [47]:
from sklearn.linear_model import LogisticRegression
regModel = LogisticRegression()
regModel.fit(X_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [48]:
predictions = regModel.predict(X_test)
predictions

array([0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       1, 0])

In [49]:
from sklearn.metrics import accuracy_score
accuracy_score(predictions,y_test)

0.8432835820895522

In [50]:
from sklearn.metrics import confusion_matrix
confusion_matrix(predictions,y_test)

array([[79, 19],
       [ 2, 34]])

In [51]:
from sklearn.metrics import classification_report
classification_report(predictions, y_test)

'             precision    recall  f1-score   support\n\n          0       0.98      0.81      0.88        98\n          1       0.64      0.94      0.76        36\n\navg / total       0.89      0.84      0.85       134\n'

In [52]:
# print(predictions)
# print(y_test)